on:
  pull_request:
    branches:
      - develop

name: Transition Issue

jobs:
  test-transition-issue:
    name: Transition Issue
    runs-on: ubuntu-latest
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        
    - name: Find in commit messages
      id: find
      uses: atlassian/gajira-find-issue-key@master
      with:
        string1: ${{ github.event.pull_request.title, github.event.pull_request.description }}
        
    - name: Transition issue
      uses: atlassian/gajira-transition@master
      if: ${{ steps.find.outputs.issue }}
      with:
        issue: ${{ steps.find.outputs.issue }}
        transition: "REVIEW"
